version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/server/conf.d:/etc/nginx/conf.d
    ports:
      - "5000:80"
    depends_on:
      - app
    container_name: webserver

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    user: "1000:33"
    depends_on:
      - db
    volumes:
      - ./:/var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
        use_compression=1
    container_name: app

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    container_name: db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.net
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    container_name: pgadmin
